### PR TITLE
Fix #165

### LINKED ISSUE #165: Close parenthesis causes crash
**Describe the bug**
Whenever a unnecessary close parenthesis is entered the web app will crash

**To Reproduce**
1. Go to The web app
2. Type ")"
3. See error

**Expected behavior**
You should be able to type parenthesis as normal.

**Screenshots**
If applicable, add screenshots to help explain your problem. For Oasis Web, browser console logs are useful. For Oasis Desktop, please provide crash dumps from your operating system.

**Desktop (please complete the following information):**
 - Version [e.g. 22 or commit hash]

**Web (please complete the following information):**
 - Device: Thinkpad
 - OS: Windows 11
 - Browser: Chrome
 - Version: 136

**Additional context**
It will not cause an error when inputted with certain equations like 5*(4+3) wont result in an error but (4+3) will.

### PR DESCRIPTION
**Pull request by matthew-mccall**
### Summary

- Simplified parentheses and function operation logic in `FromString.cpp` to improve code clarity and maintainability.
- Added new parsing tests to validate behavior with mismatched and valid parentheses.
- Introduced a utility operator in `InFixTests.cpp` to streamline test cases.

Fixes #165

### CODE REVIEW

File: io/tests/InFixTests.cpp [hunk 1]
```diff
@@ -92,4 +100,20 @@ TEST_CASE("In-Fix Preprocessor Works with Implicit Multiplication and Functions"
...
+}
+
+TEST_CASE("In-Fix Works With Parenthesis", "[Parsing]")
+{
+    const auto expected = Oasis::Add { Oasis::Real { 4 }, Oasis::Real { 3 } };
+
+    auto InFixWithDefaultArgs = [](const std::string& in) { return Oasis::FromInFix(in); };
+    const auto result = std::string{ "(4+3)" } | Oasis::PreProcessInFix | InFixWithDefaultArgs;
+    REQUIRE(result.has_value());
+    REQUIRE(result.value()->Equals(expected));
```
Comment (matthew-mccall) [inline io/tests/InFixTests.cpp:118]: @Sam-Anderson05 Do these two test cases cover the issues you found? If not, let me know what else I should add

Comment (Sam-Anderson05) [reply io/tests/InFixTests.cpp:118]: This is good

File: io/tests/InFixTests.cpp [hunk 2]
```diff
@@ -10,6 +12,12 @@
 #include "Oasis/FromString.hpp"
 #include "Oasis/Variable.hpp"
 
+template <typename FnT>
+auto operator|(const std::string& str, FnT fn) -> boost::callable_traits::return_type_t<FnT>
```
Comment (404Naz) [inline io/tests/InFixTests.cpp:16]: Basically an "and then..." function?

**Review by 404Naz — APPROVED** [review]

File: io/tests/InFixTests.cpp (hunk 2 above)
Comment (matthew-mccall) [reply io/tests/InFixTests.cpp:16]: That's one way of putting it. The idea is that it works like shell pipes.
